# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='test_title',
        ),
    ]
