# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20170205_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=512)),
                ('multi', models.BooleanField(default=False)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Test')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.DeleteModel(
            name='Qustion',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Відповіді', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_title',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testing',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Question'),
        ),
    ]
