# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20170205_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
