# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0008_auto_20170206_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False, verbose_name='Значення відповіді')),
            ],
            options={
                'verbose_name': 'Відповіді користувача',
                'verbose_name_plural': 'Відповіді користувачів',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Запитання', 'verbose_name_plural': 'Запитання'},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'verbose_name': 'Тестування', 'verbose_name_plural': 'Результати тестів'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_title',
            field=models.TextField(verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Question', verbose_name='Запитання'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.TextField(verbose_name='Запитання'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='Тема тестування'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_title',
            field=models.CharField(max_length=255, verbose_name='Тема тестування'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='Тема тестування'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Answer', verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Question', verbose_name='Запитання'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='testing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Testing', verbose_name='Тестування'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
