# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20170206_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='testing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Testing', verbose_name='Тестування'),
        ),
    ]
